version = "3.11.5"
runner.dialect = "scala3"

encoding = "UTF-8"
project.git = true

preset=IntelliJ
align.preset = more

maxColumn = 120
lineEndings = unix
assumeStandardLibraryStripMargin = true

danglingParentheses.preset = true
rewrite.trailingCommas.style = multiple

comments {
  wrap = standalone
  wrapStandaloneSlcAsSlc = true
  wrapSingleLineMlcAsSlc = true
}

rewrite.rules = [
  Imports,
  SortModifiers
]

rewrite.sortModifiers.preset = styleGuide

rewrite.imports {
  selectors = fold
  sort = scalastyle
  groups = [
    ["java\\..*", "javax\\..*"],
    ["scala\\..*"],
    [
      "chisel3\\..*",
      "circt\\..*",
      "firrtl\\..*",
      "mill\\..*",
      "org\\..*",
      "com\\..*",
      "io\\..*"
    ],
    ["chipmunk\\..*"]
  ]
  sortCatchallGroup = tail
  removeRedundantSelectors = true
}
