name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v8

      - name: Setup Mill
        uses: zhutmost/setup-mill@main

      - name: Check compilation
        run:
          mill __.compile

      - name: Check formatting
        run:
          mill __.checkFormat

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Verilator
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: verilator
          version: 1.0

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v8

      - name: Setup Mill
        uses: zhutmost/setup-mill@main

      - name: Run tests
        run:
          mill __.test

  submit-dependencies:
    if: github.ref == 'refs/heads/main'
    needs: [code-check, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v8

      - name: Setup Mill
        uses: zhutmost/setup-mill@main

      - name: Submit dependency graph
        uses: zhutmost/mill-dependency-graph@v1
        with:
          correlator: chipmunk/dependencies
